const texts = {
  "it": {
      "1": "Accedi",
      "2": "Impostazioni",
      "3": "Muoviti facilmente all'interno della città",
      "4": "Offriamo un vasto assortimento di biciclette",
      "5": "Come funziona?",
      "6": "Perché /SHIFT?",
      "7": "Piani e tariffe",
      "8": "Piano Gratuito",
      "9": "Accesso a tutti i veicoli;",
      "10": "Assistenza 24/7;",
      "11": "Abilita la guida tramite NFC;",
      "12": "Scegli Gratuito",
      "13": "Piano Abituale",
      "14": "Piano Gratuito +",
      "15": "Prenotazione in base alla posizione attuale;",
      "16": "Prezzi ridotti;",
      "17": "Scegli Abituale",
      "18": "Piano Abituale +",
      "19": "Prenotazione (data, ora, posizione);",
      "20": "Andare a lavoro non è mai stato così facile, ritira il tuo veicolo ogni mattina presso il parcheggio /SHIFT più vicino;",
      "21": "Riserva il veicolo per il tempo della spesa al supermercato;",
      "22": "Scegli Premium",
      "23": "Questo sito utilizza cookie",
      "24": "tecnici",
      "25": "analitici",
      "26": "e di",
      "27": "profilazione",
      "28": "",
      "29": "Cookie tecnici",
      "30": "sono necessari per il corretto funzionamento del sito",
      "31": "Cookie analitici",
      "32": "ci permettono di monitorare le performance del sito e di migliorare l'esperienza degli utenti",
      "33": "Cookie di profilazione",
      "34": "usati per personalizzare l'interfaccia del sito (light/dark mode, lingua, ecc.). Per maggiori informazioni, consulta la nostra",
      "35": "Accetta tutti i cookie",
      "36": "Piano Premium",
      "37": "Contatti",
      "38": "Chi siamo",
      "39": "Servizi",
      "40": "Dove operiamo",
      "41": "Sedi",
      "42": "Informazioni legali",
      "43": "Cookie",
      "44": "Tutti i diritti riservati",
  },
  "en": {
      "1": "Sign in",
      "2": "Settings",
      "3": "Move easily within the city",
      "4": "We offer a wide assortment of bikes",
      "5": "How it works?",
      "6": "Why /SHIFT?",
      "7": "Plans and rates",
      "8": "Free Plan",
      "9": "Access to all vehicles;",
      "10": "Assistance 24/7;",
      "11": "Enable driving via NFC;",
      "12": "Choose Free",
      "13": "Regular Plan",
      "14": "Free Plan +",
      "15": "Reservation according to the current location;",
      "16": "Reduced prices;",
      "17": "Choose regular",
      "18": "Regular Plan +",
      "19": "Reservation (date, time, location);",
      "20": "Going to work has never been easier, pick up your vehicle every morning at the nearest /SHIFT vehicle park;",
      "21": "Reserve the vehicle for supermarket shopping time;",
      "22": "Choose Premium",
      "23": "This website uses ",
      "24": "technical",
      "25": "analytical",
      "26": "and",
      "27": "profiling",
      "28": "cookies",
      "29": "Technical",
      "30": "cookies are necessary for the correct functioning of the site",
      "31": "Analytical",
      "32": "cookies allow us to monitor site performance and improve the user experience",
      "33": "Profiling",
      "34": "cookies are used to personalize the site interface (light/dark mode, language, etc.). For more information, please see our",
      "35": "Accept all cookies",
      "36": "Premium Plan",
      "37": "Contacts",
      "38": "About us",
      "39": "Services",
      "40": "Where we operate",
      "41": "Locations",
      "42": "Legal informations",
      "43": "Cookies",
      "44": "All rights reserved",
      
      
      
  },
  "es": {
      "1": "Acceso",
      "2": "Ajustes",
      "3": "Muévete fácilmente dentro de la ciudad",
      "4": "Ofrecemos una amplia variedad de bicicletas.",
      "5": "¿Cómo funciona?",
      "6": "¿Por qué /SHIFT?",
      "7": "Planes y tarifas",
      "8": "Plan gratuito",
      "9": "Acceso a todos los vehículos;",
      "10": "Asistencia 24/7;",
      "11": "Habilitar la conducción a través de NFC;",
      "12": "Elige gratis",
      "13": "Plan Abitual",
      "14": "Plan gratuito +",
      "15": "Reserva según la ubicación actual;",
      "16": "Precios reducidos;",
      "17": "Elige Abitual",
      "18": "Plan Abitual +",
      "19": "Reserva (fecha, hora, lugar);",
      "20": "Ir a trabajar nunca ha sido tan fácil, recoge tu vehículo cada mañana en el parking /SHIFT más cercano;",
      "21": "Reserva el vehículo para el momento de comprar en el supermercado;",
      "22": "Elige Premium",
      "23": "Este sitio web utiliza cookie ",
      "24": "tecnicos",
      "25": "analíticos",
      "26": "y",
      "27": "de perfiles",
      "28": "",
      "29": "Cookie tecnicos",
      "30": "son necesarios para el correcto funcionamiento del sitio",
      "31": "Cookie analíticos",
      "32": "permitirnos monitorear el rendimiento del sitio y mejorar la experiencia del usuario",
      "33": "Cookie de perfiles",
      "34": "se utilizan para personalizar la interfaz del sitio (modo claro/oscuro, idioma, etc.). Para obtener más información, consulte nuestro",
      "35": "aceptar todas las cookie",
      "36": "Plan Premium",
      "37": "Contactos",
      "38": "Quienes somos",
      "39": "Servicios",
      "40": "Donde operamos",
      "41": "Ubicaciones",
      "42": "Informaciones legales",
      "43": "Cookie",
      "44": "Reservados todos los derechos",
  }
};
